"""Semantic colors shared by built-in themes and the theme editor."""

LIGHT = {
    "workspace_bg": "#f1f3f4",
    "editor_bg": "#ffffff",
    "text_color": "#202124",
    "toolbar_bg": "#f8f9fa",
    "toolbar_border": "#dadce0",
    "menu_bg": "#f8f9fa",
    "menu_hover": "#e8eaed",
    "button_bg": "#ffffff",
    "button_hover": "#e8eaed",
    "button_active": "#d2e3fc",
    "accent": "#1a73e8",
    "accent_text": "#1967d2",
    "scrollbar_bg": "#f1f3f4",
    "scrollbar_handle": "#9aa0a6",
    "tab_active_bg": "#ffffff",
    "tab_inactive_bg": "#f8f9fa",
    "border_color": "#dadce0",
    "footer_bg": "#f8f9fa",
    "page_shadow": "#dadce0",
}
DARK = {
    "workspace_bg": "#1a1a1d",
    "editor_bg": "#2d2d30",
    "text_color": "#e8eaed",
    "toolbar_bg": "#303134",
    "toolbar_border": "#3c4043",
    "menu_bg": "#303134",
    "menu_hover": "#3c4043",
    "button_bg": "#303134",
    "button_hover": "#3c4043",
    "button_active": "#1a3654",
    "accent": "#8ab4f8",
    "accent_text": "#8ab4f8",
    "scrollbar_bg": "#202124",
    "scrollbar_handle": "#70757a",
    "tab_active_bg": "#2d2d30",
    "tab_inactive_bg": "#202124",
    "border_color": "#3c4043",
    "footer_bg": "#303134",
    "page_shadow": "#3c4043",
}
PALETTES = {"light": LIGHT, "dark": DARK}
